apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: argocd
spec:
  project: default  # Specifies the ArgoCD project
  destination:
    namespace: api  # Ensures the correct namespace is used
    server: https://kubernetes.default.svc  # Fixes incorrect URL
  source:
    repoURL: https://github.com/mirar123/api-app.git
    targetRevision: main
    path: fastapi-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

